### ISSUE TITLE
Notes for the readme

### ISSUE THREAD

**Issue by kvansaders** [lekkimworld/salesforce-azure-clientcredentials-authprovider#2]
Great work! This is exactly what I needed.

For the readme, there are two issues I ran into that should be mentioned that someone would have to configure, since the errors on the Salesforce side aren't always too helpful.

1) In Azure AD in the Portal, the FQDN of the callback url needs to be added in the app registration to the section Authentication -> Web ->Redirect URI's

2) In Salesforce, make sure that "https://login.microsoftonline.com/{your tenant}" is added to the Remote Sites list.  With the built-in providers we normally we wouldn't have to do this, but since the custom Apex relies on POST calls, this was my last snag that I hit.  
    
    At least the debug logs could show me this.
    System.CalloutException: Unauthorized endpoint, please check Setup->Security->Remote site settings. endpoint = https://login.microsoftonline.com/...

**Comment by lekkimworld** [comment]
@kvansaders this is great feedback and happy that you found the auth provider helpful. The metadata in the project already has a remote site setting for both https://graph.microsoft.com and for https://login.microsoftonline.com - did you deploy these? Just wondering. I'll add the bit about adding the FQDN of the callback url to the app registration in Azure.

Thank you.

**Comment by kvansaders** [comment]
@lekkimworld ,
I guess I didn't see that folder for the remote site setting.  Anyway, thanks again for sharing this with the world!

**Comment by kvansaders** [comment]
accidentially hit close with my last comment.

**Comment by lekkimworld** [comment]
No worries. I'll commit the updated readme now.
